POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "qweqwqe@55gmail.com",
	"password": "helloworld"
}

###

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name": "qwe",
    "email": "qweqwqe@55gmail.com",
	"password": "helloworld"
}